# Generated by Django 3.2 on 2021-04-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='usersignupp',
        ),
    ]
