# Generated by Django 3.2 on 2021-05-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0004_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=1000, unique=True, verbose_name='email'),
        ),
        migrations.AlterModelTable(
            name='account',
            table='signupform',
        ),
    ]
