# Generated by Django 3.2 on 2021-05-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0006_auto_20210503_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=250, unique=True, verbose_name='email'),
        ),
    ]
