# Generated by Django 3.2 on 2021-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0010_alter_account_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CLOTHES', 'Clothes'), ('ELECTRONICS', 'Electronics'), ('BOOKS', 'Books'), ('SHOES', 'Shoes')], max_length=200)),
                ('productname', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'pro',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='phone_no',
            field=models.CharField(default=1234567891, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
