# Generated by Django 3.2 on 2021-06-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
