# Generated by Django 3.2 on 2021-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0013_auto_20210602_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('products_list', models.ManyToManyField(blank=True, null=True, to='tryapp.Product')),
            ],
        ),
    ]
