# Generated by Django 3.2 on 2021-06-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0015_auto_20210602_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
