# Generated by Django 3.2 on 2021-06-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0017_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='update_on',
        ),
    ]
