# Generated by Django 3.2 on 2021-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0018_auto_20210604_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
