# Generated by Django 3.2 on 2021-06-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0019_auto_20210604_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
    ]
